### ISSUE TITLE
I ACCIDENTALLY THE COMMIT HISTORY

### ISSUE THREAD

**Issue by Errorcrafter** [Bakdooro/Bakdooro#14]
right so i kept getting this error for some reason so my dumbass decided to forcepush
![image](https://user-images.githubusercontent.com/69189354/141460731-a2eb3fec-f7cd-4957-b809-55e7082c5792.png)
and commit history went bye bye im so sorry aaaaaaaaaaaaaa

**Comment by Errorcrafter** [comment]
ok i still have the hash for the previous commit i think its `5896479` according to my terminal so im going to try to resotre it with the reflog

**Comment by Errorcrafter** [comment]
i managed to get a small amou t of it back

fuck this shit enjoy having only 5 fucking commits git is black magic anyway

**Comment by Errorcrafter** [comment]
@AcaiBerii @Unknown-User2 if either of you have a local copy of anything upload it now

**Comment by AcaiBerii** [comment]
NOOOOOOOOOOOOOOOOOOOOOO WHYYYYY  
also i have all the previous commit history locally so i can get it back  
you just have to recommit everything  
also just search it on stackoverflow smh >:(

**Comment by AcaiBerii** [comment]
ok i restored the commit history smh  
just make your changes again

https://www.akashmittal.com/error-src-refspec-master-not-match/ should also help you gotta commit/pull changes...

**Comment by AcaiBerii** [comment]
@Errorcrafter can you please recommit your changes into a new branch and pull them in?

**Comment by Errorcrafter** [comment]
will do soon

**Comment by AcaiBerii** [comment]
> > soon
> soon
soon

**Comment by BalaM314** [comment]
imagine not knowing how to use git

**Comment by AcaiBerii** [comment]
@Errorcrafter please push your commits or i will archive this repository/

**Comment by Errorcrafter** [comment]
sorry away from home atm

**Comment by AcaiBerii** [comment]
When are you planning to be back?

**Comment by Errorcrafter** [comment]
i dont know

btw for bakdooro installer we have to use discord webhooks since directly sebdibg to to the console app would prolly require some port fwding bullshit

**Comment by AcaiBerii** [comment]
oh...

**Comment by Errorcrafter** [comment]
okay im back and ive recommitted the shit
