### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by erxson** [Bakdooro/Bakdooro#15]
![image](https://user-images.githubusercontent.com/50082485/144379380-7342a132-a56d-4ecc-a4d4-9d9d084366cb.png)

**Comment by Errorcrafter** [comment]
i havent pudated the plugin for 1.18 yet, will do soon

**Comment by Errorcrafter** [comment]
though this may be a cimpletely different problem lol

**Comment by erxson** [comment]
Oh, sorry

**Comment by AcaiBerii** [comment]
```
p is null
```
we've ruined the code quite a considerable amount.

**Comment by Errorcrafter** [comment]
fuck i didnt see that

erxson is it possible to provide the full stacktrace to see where i fucked up

**Comment by AcaiBerii** [comment]
fixed
