### ISSUE TITLE
THEY MADE QLUTCH FREE

### ISSUE THREAD

**Issue by acaiberii** [Bakdooro/Bakdooro#16]
## Describe the error
![https://c.tenor.com/-wrmUJrUbeoAAAAC/emoji-disintergrating.gif](https://c.tenor.com/-wrmUJrUbeoAAAAC/emoji-disintergrating.gif)

OUR PROJECT IS NOW COMPLETELY USELESS 😡😡😡

**Comment by erxson** [comment]
free version is useless

**Comment by erxson** [comment]
dont worry

**Comment by Errorcrafter** [comment]
wait whaaaaat?

**Comment by Errorcrafter** [comment]
i think qlutch's site is being overloaded with people getting the free version, its not loading at all and i cant read anything about free plan features bruh

**Comment by Errorcrafter** [comment]
![image](https://user-images.githubusercontent.com/69189354/147406930-9b708ab0-f124-4392-80d4-8ac86a69b434.png)

top fucking tier web design

**Comment by acaiberii** [comment]
![bruhmoment2020](https://i-dont.go-outsi.de/5jw4jgf8E.png)

top fucking tier pricing

**Comment by Errorcrafter** [comment]
ah well this project has been dead for a while since java is an absolutely insufferable language

fuck this

**Comment by acaiberii** [comment]
nah i've totally been trying to maintain it 100%...
